"""Report generators: PROGRESS.md, FOUNDATIONS.md, RESULTS.md, TOOLKIT.md."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from . import config as _cfg
from .db import build_db
from .frontmatter import get_body, readable_id


def _primary_claim_path_sql(column: str = "file_path") -> str:
    return f"({column} LIKE 'claims/claim-%/claim.md' OR {column} LIKE 'cycles/%/frontier.md')"

# ---------------------------------------------------------------------------
# Command: status -> PROGRESS.md
# ---------------------------------------------------------------------------


def cmd_status(args: argparse.Namespace) -> None:
    """Auto-generate PROGRESS.md from the DB."""
    conn = build_db()  # Always rebuild for freshness

    lines = [
        "# Design Progress",
        "",
        "> Auto-generated by `manage.py status`. Do not edit manually.",
        "",
    ]

    # --- Current blockers ---
    # Active nodes that have dependents still pending
    blockers = conn.execute("""
        SELECT n.id, n.file_path, n.title,
               COUNT(DISTINCT e.source_id) as blocked_count
        FROM nodes n
        JOIN edges e ON e.target_id = n.id AND e.relation IN ('depends_on', 'assumes')
        JOIN nodes dep ON dep.id = e.source_id AND dep.status = 'pending'
            AND (dep.file_path LIKE 'claims/claim-%/claim.md' OR dep.file_path LIKE 'cycles/%/frontier.md')
        WHERE n.status = 'active'
          AND (
              n.type = 'assumption'
              OR n.file_path LIKE 'claims/claim-%/claim.md'
              OR n.file_path LIKE 'cycles/%/frontier.md'
          )
        GROUP BY n.id
        ORDER BY blocked_count DESC
    """).fetchall()

    lines.append("## Current blockers")
    lines.append("")
    if blockers:
        for b in blockers:
            title = b["title"] or readable_id(b["id"])
            lines.append(f"- **{title}** (`{b['id']}`) -- blocks {b['blocked_count']} pending node(s)")
            lines.append(f"  File: {b['file_path']}")
    else:
        # Fallback: any active node
        active = conn.execute(
            f"SELECT * FROM nodes WHERE status = 'active' AND {_primary_claim_path_sql()} ORDER BY date"
        ).fetchall()
        if active:
            for a in active:
                title = a["title"] or readable_id(a["id"])
                lines.append(f"- **{title}** (`{a['id']}`)")
                lines.append(f"  File: {a['file_path']}")
        else:
            lines.append("No active blockers.")
    lines.append("")

    # --- Proven ---
    lines.append("## What is proven")
    lines.append("")
    proven = conn.execute("SELECT * FROM nodes WHERE status = 'proven' ORDER BY file_path").fetchall()
    if proven:
        lines.append("| Claim | Source |")
        lines.append("|-------|--------|")
        for s in proven:
            title = s["title"] or readable_id(s["id"])
            lines.append(f"| {title} | `{s['id']}` |")
        lines.append("")
    else:
        lines.append("Nothing proven yet.")
        lines.append("")

    # --- Disproven ---
    lines.append("## What is disproven")
    lines.append("")
    falsified = conn.execute(
        "SELECT n.*, e.target_id as evidence_id "
        "FROM nodes n "
        "LEFT JOIN edges e ON e.source_id = n.id AND e.relation = 'falsified_by' "
        "WHERE n.status = 'disproven' "
        "ORDER BY n.file_path"
    ).fetchall()
    if falsified:
        lines.append("| Node | File | Falsified by |")
        lines.append("|------|------|-------------|")
        for f in falsified:
            title = f["title"] or readable_id(f["id"])
            eby = f["evidence_id"] or "--"
            lines.append(f"| {title} | `{f['file_path']}` | `{eby}` |")
        lines.append("")
    else:
        lines.append("Nothing disproven.")
        lines.append("")

    # --- Assumptions ---
    lines.append("## Assumptions")
    lines.append("")
    assumptions = conn.execute("SELECT * FROM nodes WHERE type = 'assumption' ORDER BY date").fetchall()
    if assumptions:
        lines.append("| ID | Status | Dependents |")
        lines.append("|----|--------|------------|")
        for a in assumptions:
            dep_count = conn.execute(
                "SELECT COUNT(*) as c FROM edges WHERE target_id = ? AND relation = 'assumes'",
                (a["id"],),
            ).fetchone()["c"]
            lines.append(f"| `{a['id']}` | {a['status']} | {dep_count} |")
        lines.append("")
    else:
        lines.append("No assumptions registered.")
        lines.append("")

    lines.append("## Claim log")
    lines.append("")
    claim_nodes = conn.execute(
        "SELECT * FROM nodes "
        f"WHERE {_primary_claim_path_sql()} "
        "ORDER BY file_path"
    ).fetchall()
    if claim_nodes:
        lines.append("| Claim | Status | File |")
        lines.append("|-------|--------|------|")
        for n in claim_nodes:
            title = n["title"] or readable_id(n["id"])
            lines.append(f"| {title} | {n['status']} | `{n['file_path']}` |")
        lines.append("")
    else:
        lines.append("No claims registered.")
        lines.append("")

    # --- Next action ---
    lines.append("## Next action")
    lines.append("")
    pending = conn.execute("SELECT * FROM nodes WHERE status = 'pending' ORDER BY file_path LIMIT 1").fetchone()
    if pending:
        title = pending["title"] or readable_id(pending["id"])
        lines.append(f"First pending: **{title}** (`{pending['id']}`)")
        lines.append(f"File: `{pending['file_path']}`")
    else:
        lines.append("No pending nodes.")
    lines.append("")

    content = "\n".join(lines) + "\n"
    _cfg._atomic_write(_cfg.PROGRESS_PATH, content)
    print(f"Generated: {_cfg.PROGRESS_PATH}")


# ---------------------------------------------------------------------------
# Command: assumptions -> FOUNDATIONS.md
# ---------------------------------------------------------------------------


def cmd_assumptions(args: argparse.Namespace) -> None:
    """Auto-generate FOUNDATIONS.md."""
    conn = build_db()  # Always rebuild for freshness

    lines = [
        "# Foundations",
        "",
        "> Auto-generated by `manage.py assumptions`. Do not edit manually.",
        "",
    ]

    assumptions = conn.execute("SELECT * FROM nodes WHERE type = 'assumption' ORDER BY date, id").fetchall()

    if not assumptions:
        lines.append("No assumptions registered in the database.")
        lines.append("")
        lines.append("To register assumptions, add `type: assumption` to a file's frontmatter,")
        lines.append("and reference it via `assumes: [<id>]` in dependent files.")
    else:
        for a in assumptions:
            lines.append(f"## `{a['id']}`")
            lines.append("")
            lines.append(f"- **Status**: {a['status']}")
            lines.append(f"- **Date introduced**: {a['date']}")
            lines.append(f"- **File**: `{a['file_path']}`")

            # What depends on it
            dependents = conn.execute(
                "SELECT source_id FROM edges WHERE target_id = ? AND relation = 'assumes'",
                (a["id"],),
            ).fetchall()
            if dependents:
                lines.append(f"- **Depended on by**: {', '.join('`' + d['source_id'] + '`' for d in dependents)}")
            else:
                lines.append("- **Depended on by**: (none)")

            # If disproven
            if a["status"] == "disproven":
                evidence = conn.execute(
                    "SELECT target_id FROM edges WHERE source_id = ? AND relation = 'falsified_by'",
                    (a["id"],),
                ).fetchone()
                if evidence:
                    lines.append(f"- **Falsified by**: `{evidence['target_id']}`")

                # What was cascaded
                cascaded = conn.execute(
                    "SELECT n.id, n.status FROM nodes n "
                    "JOIN edges e ON e.source_id = n.id AND e.target_id = ? AND e.relation = 'assumes' "
                    "WHERE n.status IN ('partial', 'weakened')",
                    (a["id"],),
                ).fetchall()
                if cascaded:
                    lines.append(f"- **Cascade**: {', '.join('`' + c['id'] + '`' for c in cascaded)} weakened")
            lines.append("")

    content = "\n".join(lines) + "\n"
    _cfg._atomic_write(_cfg.FOUNDATIONS_PATH, content)
    print(f"Generated: {_cfg.FOUNDATIONS_PATH}")


# ---------------------------------------------------------------------------
# Command: codebook -> TOOLKIT.md
# ---------------------------------------------------------------------------


def cmd_codebook(args: argparse.Namespace) -> None:
    """Generate TOOLKIT.md from the coder artifacts registry."""
    conn = build_db()
    rows = conn.execute("SELECT * FROM coder_artifacts ORDER BY artifact_type, name").fetchall()

    lines = [
        "# Experiment Toolkit",
        "",
        "> Auto-generated from the experiment artifacts registry. Do not edit manually.",
        "",
    ]

    if not rows:
        lines.append("No artifacts registered yet.")
    else:
        by_type: dict[str, list] = {}
        for r in rows:
            by_type.setdefault(r["artifact_type"], []).append(r)

        for atype in sorted(by_type):
            lines.append(f"## {atype.title()}s")
            lines.append("")
            for r in by_type[atype]:
                lines.append(f"### `{r['id']}` — {r['name']}")
                lines.append(f"- **File**: `{r['file_path']}`")
                if r["description"]:
                    lines.append(f"- **Description**: {r['description']}")
                if r["dependencies"]:
                    lines.append(f"- **Dependencies**: {r['dependencies']}")
                if r["created_by"]:
                    lines.append(f"- **Created by**: cycle `{r['created_by']}`")
                lines.append(f"- **Date**: {r['created_at']}")
                lines.append("")

    content = "\n".join(lines) + "\n"
    codebook_path = _cfg.RESEARCH_DIR / "TOOLKIT.md"
    _cfg._atomic_write(codebook_path, content)
    print(f"Generated: {codebook_path}")


# ---------------------------------------------------------------------------
# Helper: investigation breadcrumb
# ---------------------------------------------------------------------------


def _format_investigation_breadcrumb(state: dict[str, Any], research_dir: Path) -> str:
    """Format a breadcrumb string for the current investigation state."""
    phase = state.get("phase", "")
    action = state.get("action", "")

    # Read north star title if exists
    ns_path = research_dir / ".north-star.md"
    north_star = ""
    if ns_path.exists():
        body = get_body(ns_path.read_text(encoding="utf-8"))
        first_line = body.strip().split("\n")[0].lstrip("# ").strip()
        north_star = first_line[:80]

    parts: list[str] = []

    if phase == "understand":
        substeps = state.get("substeps", [])
        current = substeps[0].title() if substeps else "Complete"
        parts.append(f"[Understand > {current}]")
        remaining = ", ".join(s for s in substeps[1:])
        if remaining:
            parts.append(f"  Next: {remaining}")
    elif phase == "divide":
        if action == "scaffold":
            n = len(state.get("claims", []))
            parts.append(f"[Divide > Scaffold] {n} claims to scaffold")
        else:
            parts.append("[Divide] Decomposing into testable claims")
    elif phase == "test":
        cycle = state.get("cycle", "")
        if action == "test_claim":
            parts.append(f"[Test > {cycle}] Dispatching conductor")
        elif action == "record_verdict":
            parts.append(f"[Test > {cycle}] Recording verdict")
    elif phase == "synthesize":
        n = len(state.get("proven_claims", []))
        parts.append(f"[Synthesize] Composing from {n} proven claims")
    elif phase == "complete":
        parts.append("[Complete] Design process finished")

    if north_star:
        parts.append(f'  North star: "{north_star}"')

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Command: results -> RESULTS.md
# ---------------------------------------------------------------------------


def cmd_results(args: argparse.Namespace) -> None:
    """Generate a single RESULTS.md summarising the entire design investigation."""
    conn = build_db()

    lines: list[str] = ["# Design Results", ""]

    # --- Original question/principle ---
    # Try to read from blueprint or framework
    for name in ("blueprint.md",):
        bp = _cfg.RESEARCH_DIR / name
        if bp.exists():
            body = get_body(bp.read_text(encoding="utf-8"))
            # Extract first paragraph as the principle
            para = []
            for line in body.splitlines():
                if line.strip():
                    para.append(line.strip())
                elif para:
                    break
            if para:
                lines.append("## Principle")
                lines.append("")
                lines.extend(para)
                lines.append("")
            break

    # --- Claims and verdicts ---
    lines.append("## Claims")
    lines.append("")

    from .orchestration import extract_confidence, extract_verdict, load_config

    orch_config = load_config(_cfg.DEFAULT_ORCH_CONFIG)
    # Scan verdict files directly — DB frontmatter status is unreliable
    # (verdict nodes typically have status: active, not the actual verdict)
    found_verdicts = False
    for root_dir in (_cfg.RESEARCH_DIR / "claims", _cfg.RESEARCH_DIR / "cycles"):
        if not root_dir.exists():
            continue
        for verdict_file in sorted(root_dir.rglob("verdict.md")):
            found_verdicts = True
            claim_dir = verdict_file.parent.parent.parent  # arbiter/results/verdict.md → claim dir
            claim_name = claim_dir.name
            verdict_val = extract_verdict(verdict_file, orch_config)
            confidence_val = extract_confidence(verdict_file)
            lines.append(f"### {claim_name}")
            lines.append(f"- **Verdict**: {verdict_val}")
            lines.append(f"- **Confidence**: {confidence_val}")
            lines.append("")

    if not found_verdicts:
        lines.append("No claims investigated yet.")
        lines.append("")

    # --- Synthesis ---
    synthesis = _cfg.RESEARCH_DIR / "synthesis.md"
    if synthesis.exists():
        lines.append("## Synthesis")
        lines.append("")
        body = get_body(synthesis.read_text(encoding="utf-8"))
        lines.append(body.strip())
        lines.append("")

    # --- Composition ---
    composition = _cfg.RESEARCH_DIR / "composition.md"
    if composition.exists():
        lines.append("## Composed Algorithm")
        lines.append("")
        body = get_body(composition.read_text(encoding="utf-8"))
        lines.append(body.strip())
        lines.append("")

    # --- Limitations ---
    lines.append("## Limitations")
    lines.append("")

    disproven = conn.execute("SELECT id FROM nodes WHERE status = 'disproven' ORDER BY id").fetchall()
    if disproven:
        lines.append("**Disproven claims**:")
        for row in disproven:
            lines.append(f"- {row['id']}")
        lines.append("")

    pending_assumptions = conn.execute(
        "SELECT id FROM nodes WHERE type = 'assumption' AND status = 'pending' ORDER BY id"
    ).fetchall()
    if pending_assumptions:
        lines.append("**Untested assumptions**:")
        for row in pending_assumptions:
            lines.append(f"- {row['id']}")
        lines.append("")

    weakened = conn.execute("SELECT id FROM nodes WHERE status IN ('partial', 'weakened') ORDER BY id").fetchall()
    if weakened:
        lines.append("**Partially supported / weakened**:")
        for row in weakened:
            lines.append(f"- {row['id']}")
        lines.append("")

    if not disproven and not pending_assumptions and not weakened:
        lines.append("None identified.")
        lines.append("")

    # --- Write ---
    content = "\n".join(lines) + "\n"
    results_path = _cfg.RESEARCH_DIR / "RESULTS.md"
    _cfg._atomic_write(results_path, content)
    print(f"Generated: {results_path}")
